# =======================
# Configuration Globale
# =======================

lunarcrush:
  api_key: "85zhfo9yl9co22cl7kw2sucossm59awchvwf8s8ub"

# On n'utilise plus Coinbase => retire ou laisse en pass
coinbase:
  pass: "none"

# Paramètres d'échange
exchanges:
  binance:
    symbol_mapping:
      "0G": "0G"
      "1INCH": "1INCH"
      "2Z": "2Z"
      "A": "A"
      "A2Z": "A2Z"
      "AAVE": "AAVE"
      "ACH": "ACH"
      "ACT": "ACT"
      "ACX": "ACX"
      "ADA": "ADA"
      "AEVO": "AEVO"
      "AIXBT": "AIXBT"
      "ALGO": "ALGO"
      "ALLO": "ALLO"
      "ALT": "ALT"
      "ANIME": "ANIME"
      "APE": "APE"
      "API3": "API3"
      "APT": "APT"
      "AR": "AR"
      "ARB": "ARB"
      "ARKM": "ARKM"
      "ASTER": "ASTER"
      "ATOM": "ATOM"
      "AUCTION": "AUCTION"
      "AVAX": "AVAX"
      "AVNT": "AVNT"
      "AXS": "AXS"
      "BABY": "BABY"
      "BANANAS31": "BANANAS31"
      "BANK": "BANK"
      "BARD": "BARD"
      "BB": "BB"
      "BCH": "BCH"
      "BERA": "BERA"
      "BIGTIME": "BIGTIME"
      "BIO": "BIO"
      "BLUR": "BLUR"
      "BMT": "BMT"
      "BNB": "BNB"
      "BOME": "BOME"
      "BONK": "BONK"
      "BTC": "BTC"
      "C": "C"
      "CAKE": "CAKE"
      "CATI": "CATI"
      "CETUS": "CETUS"
      "CFX": "CFX"
      "CGPT": "CGPT"
      "CHESS": "CHESS"
      "CHZ": "CHZ"
      "CKB": "CKB"
      "COMP": "COMP"
      "COOKIE": "COOKIE"
      "COTI": "COTI"
      "COW": "COW"
      "CRV": "CRV"
      "CVC": "CVC"
      "CVX": "CVX"
      "CYBER": "CYBER"
      "DASH": "DASH"
      "DF": "DF"
      "DOGE": "DOGE"
      "DOGS": "DOGS"
      "DOLO": "DOLO"
      "DOT": "DOT"
      "DYM": "DYM"
      "EGLD": "EGLD"
      "ENA": "ENA"
      "ENJ": "ENJ"
      "ENS": "ENS"
      "ENSO": "ENSO"
      "ERA": "ERA"
      "ETC": "ETC"
      "ETH": "ETH"
      "ETHFI": "ETHFI"
      "EUL": "EUL"
      "EURI": "EURI"
      "FDUSD": "FDUSD"
      "FET": "FET"
      "FF": "FF"
      "FIL": "FIL"
      "FLOKI": "FLOKI"
      "FLUX": "FLUX"
      "FORM": "FORM"
      "FUN": "FUN"
      "GALA": "GALA"
      "GMT": "GMT"
      "GMX": "GMX"
      "GPS": "GPS"
      "GRT": "GRT"
      "GUN": "GUN"
      "HAEDAL": "HAEDAL"
      "HBAR": "HBAR"
      "HEI": "HEI"
      "HEMI": "HEMI"
      "HIVE": "HIVE"
      "HMSTR": "HMSTR"
      "HOLO": "HOLO"
      "HOME": "HOME"
      "HUMA": "HUMA"
      "HYPER": "HYPER"
      "ICP": "ICP"
      "IDEX": "IDEX"
      "ILV": "ILV"
      "IMX": "IMX"
      "INIT": "INIT"
      "INJ": "INJ"
      "IO": "IO"
      "IOTA": "IOTA"
      "JTO": "JTO"
      "JUP": "JUP"
      "JUV": "JUV"
      "KAIA": "KAIA"
      "KAITO": "KAITO"
      "KERNEL": "KERNEL"
      "KMNO": "KMNO"
      "LDO": "LDO"
      "LINEA": "LINEA"
      "LINK": "LINK"
      "LISTA": "LISTA"
      "LPT": "LPT"
      "LSK": "LSK"
      "LTC": "LTC"
      "LUNA": "LUNA"
      "LUNC": "LUNC"
      "MAGIC": "MAGIC"
      "MANTA": "MANTA"
      "MASK": "MASK"
      "MAV": "MAV"
      "ME": "ME"
      "MEME": "MEME"
      "MINA": "MINA"
      "MORPHO": "MORPHO"
      "MOVE": "MOVE"
      "MUBARAK": "MUBARAK"
      "NEAR": "NEAR"
      "NEO": "NEO"
      "NEWT": "NEWT"
      "NIL": "NIL"
      "NMR": "NMR"
      "NOT": "NOT"
      "OM": "OM"
      "ONDO": "ONDO"
      "ONT": "ONT"
      "OP": "OP"
      "ORCA": "ORCA"
      "ORDI": "ORDI"
      "OSMO": "OSMO"
      "PARTI": "PARTI"
      "PAXG": "PAXG"
      "PENDLE": "PENDLE"
      "PENGU": "PENGU"
      "PEOPLE": "PEOPLE"
      "PEPE": "PEPE"
      "PHA": "PHA"
      "PIXEL": "PIXEL"
      "PLUME": "PLUME"
      "PNUT": "PNUT"
      "POL": "POL"
      "PROVE": "PROVE"
      "PUMP": "PUMP"
      "PUNDIX": "PUNDIX"
      "PYTH": "PYTH"
      "QNT": "QNT"
      "QTUM": "QTUM"
      "RARE": "RARE"
      "RAY": "RAY"
      "RED": "RED"
      "RENDER": "RENDER"
      "RESOLV": "RESOLV"
      "REZ": "REZ"
      "ROSE": "ROSE"
      "RPL": "RPL"
      "RSR": "RSR"
      "RUNE": "RUNE"
      "RVN": "RVN"
      "S": "S"
      "SAGA": "SAGA"
      "SAHARA": "SAHARA"
      "SAND": "SAND"
      "SAPIEN": "SAPIEN"
      "SEI": "SEI"
      "SHELL": "SHELL"
      "SHIB": "SHIB"
      "SIGN": "SIGN"
      "SKL": "SKL"
      "SKY": "SKY"
      "SNX": "SNX"
      "SOL": "SOL"
      "SOLV": "SOLV"
      "SOMI": "SOMI"
      "SOPH": "SOPH"
      "SPK": "SPK"
      "SSV": "SSV"
      "STEEM": "STEEM"
      "STO": "STO"
      "STRK": "STRK"
      "STX": "STX"
      "SUI": "SUI"
      "SUSHI": "SUSHI"
      "SXT": "SXT"
      "SYN": "SYN"
      "SYRUP": "SYRUP"
      "T": "T"
      "TAO": "TAO"
      "THE": "THE"
      "THETA": "THETA"
      "TIA": "TIA"
      "TLM": "TLM"
      "TNSR": "TNSR"
      "TON": "TON"
      "TOWNS": "TOWNS"
      "TRB": "TRB"
      "TREE": "TREE"
      "TRUMP": "TRUMP"
      "TRX": "TRX"
      "TST": "TST"
      "TURBO": "TURBO"
      "TURTLE": "TURTLE"
      "TUT": "TUT"
      "TWT": "TWT"
      "UMA": "UMA"
      "UNI": "UNI"
      "USD1": "USD1"
      "USDE": "USDE"
      "USUAL": "USUAL"
      "UTK": "UTK"
      "VANA": "VANA"
      "VANRY": "VANRY"
      "VET": "VET"
      "VIRTUAL": "VIRTUAL"
      "W": "W"
      "WAL": "WAL"
      "WCT": "WCT"
      "WIF": "WIF"
      "WLD": "WLD"
      "WLFI": "WLFI"
      "XAI": "XAI"
      "XLM": "XLM"
      "XPL": "XPL"
      "XRP": "XRP"
      "XTZ": "XTZ"
      "XVG": "XVG"
      "YB": "YB"
      "YGG": "YGG"
      "ZBT": "ZBT"
      "ZEC": "ZEC"
      "ZEN": "ZEN"
      "ZK": "ZK"
      "ZKC": "ZKC"
      "ZRO": "ZRO"

      # Si besoin, ajoute d'autres mappings => "MYTOKEN_LC": "MYTOKEN_BNB"

binance_api:
  api_key: "MLgAZHirgL3NyfYu8q2ReV9fSRmwOW17fQ3wKC99EcsXgaJUlIAlQ2afQ9UQ1rfU"
  api_secret: "FIC3JWQ4XoAPL22W0tBMbepGjjqVexToLg1wnSV26301p0PplUQ1wNQ7gf4aChlJ"

# Tokens qu'on suit en daily
tokens_daily:
  - "0G"
  - "1INCH"
  - "2Z"
  - "A"
  - "A2Z"
  - "AAVE"
  - "ACH"
  - "ACT"
  - "ACX"
  - "ADA"
  - "AEVO"
  - "AIXBT"
  - "ALGO"
  - "ALLO"
  - "ALT"
  - "ANIME"
  - "APE"
  - "API3"
  - "APT"
  - "AR"
  - "ARB"
  - "ARKM"
  - "ASTER"
  - "ATOM"
  - "AUCTION"
  - "AVAX"
  - "AVNT"
  - "AXS"
  - "BABY"
  - "BANANAS31"
  - "BANK"
  - "BARD"
  - "BB"
  - "BCH"
  - "BERA"
  - "BIGTIME"
  - "BIO"
  - "BLUR"
  - "BMT"
  - "BNB"
  - "BOME"
  - "BONK"
  - "BTC"
  - "C"
  - "CAKE"
  - "CATI"
  - "CETUS"
  - "CFX"
  - "CGPT"
  - "CHESS"
  - "CHZ"
  - "CKB"
  - "COMP"
  - "COOKIE"
  - "COTI"
  - "COW"
  - "CRV"
  - "CVC"
  - "CVX"
  - "CYBER"
  - "DASH"
  - "DF"
  - "DOGE"
  - "DOGS"
  - "DOLO"
  - "DOT"
  - "DYM"
  - "EGLD"
  - "ENA"
  - "ENJ"
  - "ENS"
  - "ENSO"
  - "ERA"
  - "ETC"
  - "ETH"
  - "ETHFI"
  - "EUL"
  - "EURI"
  - "FDUSD"
  - "FET"
  - "FF"
  - "FIL"
  - "FLOKI"
  - "FLUX"
  - "FORM"
  - "FUN"
  - "GALA"
  - "GMT"
  - "GMX"
  - "GPS"
  - "GRT"
  - "GUN"
  - "HAEDAL"
  - "HBAR"
  - "HEI"
  - "HEMI"
  - "HIVE"
  - "HMSTR"
  - "HOLO"
  - "HOME"
  - "HUMA"
  - "HYPER"
  - "ICP"
  - "IDEX"
  - "ILV"
  - "IMX"
  - "INIT"
  - "INJ"
  - "IO"
  - "IOTA"
  - "JTO"
  - "JUP"
  - "JUV"
  - "KAIA"
  - "KAITO"
  - "KERNEL"
  - "KMNO"
  - "LDO"
  - "LINEA"
  - "LINK"
  - "LISTA"
  - "LPT"
  - "LSK"
  - "LTC"
  - "LUNA"
  - "LUNC"
  - "MAGIC"
  - "MANTA"
  - "MASK"
  - "MAV"
  - "ME"
  - "MEME"
  - "MINA"
  - "MORPHO"
  - "MOVE"
  - "MUBARAK"
  - "NEAR"
  - "NEO"
  - "NEWT"
  - "NIL"
  - "NMR"
  - "NOT"
  - "OM"
  - "ONDO"
  - "ONT"
  - "OP"
  - "ORCA"
  - "ORDI"
  - "OSMO"
  - "PARTI"
  - "PAXG"
  - "PENDLE"
  - "PENGU"
  - "PEOPLE"
  - "PEPE"
  - "PHA"
  - "PIXEL"
  - "PLUME"
  - "PNUT"
  - "POL"
  - "PROVE"
  - "PUMP"
  - "PUNDIX"
  - "PYTH"
  - "QNT"
  - "QTUM"
  - "RARE"
  - "RAY"
  - "RED"
  - "RENDER"
  - "RESOLV"
  - "REZ"
  - "ROSE"
  - "RPL"
  - "RSR"
  - "RUNE"
  - "RVN"
  - "S"
  - "SAGA"
  - "SAHARA"
  - "SAND"
  - "SAPIEN"
  - "SEI"
  - "SHELL"
  - "SHIB"
  - "SIGN"
  - "SKL"
  - "SKY"
  - "SNX"
  - "SOL"
  - "SOLV"
  - "SOMI"
  - "SOPH"
  - "SPK"
  - "SSV"
  - "STEEM"
  - "STO"
  - "STRK"
  - "STX"
  - "SUI"
  - "SUSHI"
  - "SXT"
  - "SYN"
  - "SYRUP"
  - "T"
  - "TAO"
  - "THE"
  - "THETA"
  - "TIA"
  - "TLM"
  - "TNSR"
  - "TON"
  - "TOWNS"
  - "TRB"
  - "TREE"
  - "TRUMP"
  - "TRX"
  - "TST"
  - "TURBO"
  - "TURTLE"
  - "TUT"
  - "TWT"
  - "UMA"
  - "UNI"
  - "USD1"
  - "USDE"
  - "USUAL"
  - "UTK"
  - "VANA"
  - "VANRY"
  - "VET"
  - "VIRTUAL"
  - "W"
  - "WAL"
  - "WCT"
  - "WIF"
  - "WLD"
  - "WLFI"
  - "XAI"
  - "XLM"
  - "XPL"
  - "XRP"
  - "XTZ"
  - "XVG"
  - "YB"
  - "YGG"
  - "ZBT"
  - "ZEC"
  - "ZEN"
  - "ZK"
  - "ZKC"
  - "ZRO"

strategy:
  capital_initial: 1000
  buy_threshold: 0.35
  sell_threshold: 0.33
  stop_loss_pct: 0.10
  partial_take_profit_pct: 0.25
  partial_take_profit_ratio: 0.4
  trailing_trigger_pct: 1.8
  trailing_pct: 0.20
  big_gain_exception_pct: 3.0
  check_interval_seconds: 300
  daily_update_hour_utc: 2
  daily_update_minute_utc: 0

logging:
  file: "bot.log"

telegrams:
  bot_token: "7703664631:AAGC6G5sw7gMnLdQ5IdxGrymdAQEvHNflqo"
  chat_id: "7703664631"
